### ISSUE TITLE
can not login

### ISSUE THREAD

**Issue by kamaldua65** [codeurjc-students/2019-OpenViduTeaching#2]
I have latest 2.14 version of openVidu running. I installed docker image of 2019-OpenViduTeaching using 4th method as defined in documentation.
My docker-compose.override.yml file is :
`version: '3.1'

services:
    app:
       image: diegomzmn/openviduteaching:latest
       restart: on-failure
       volumes:
             - ${LOCAL_INITIAL_FILE_PATH}:${DOCKER_INITIAL_FILE_PATH}
             - ${OPENVIDU_RECORDING_PATH}:${OPENVIDU_RECORDING_PATH}
       ports:
             - "5442:8080"
       environment:
             OPENVIDU_URL: https://${DOMAIN_OR_PUBLIC_IP}
             OPENVIDU_SECRET: ${OPENVIDU_SECRET}
             INITIAL_DATA_FILE: ${DOCKER_INITIAL_FILE_PATH}
             OPENVIDU_RECORDING: ${OPENVIDU_RECORDING}
             OPENVIDU_RECORDING_PATH: ${OPENVIDU_RECORDING_PATH}`

My openVidu .env file contains
LOCAL_INITIAL_FILE_PATH=/opt/openvidu/initialpath
DOCKER_INITIAL_FILE_PATH=/opt/openvidu/dockerinitalpath

I have copied initialData.json file in both /opt/openvidu/initialpath and /opt/openvidu/dockerinitalpath folders.

Application starts at my https://myurl
But I can not login.
What do you think could be the reason.
Thanks in advance.

**Comment by DiegoMzmn** [comment]
Can you post the logs of the app? It should print the users and rooms added from the initialData.json file.
I think the issue is with the LOCAL_INITIAL_FILE_PATH and DOCKER_INITIAL_FILE_PATH variables. They should include the name of the file itself:
* LOCAL_INITIAL_FILE_PATH=/opt/openvidu/initialpath/initialData.json
* DOCKER_INITIAL_FILE_PATH=/opt/openvidu/dockerinitalpath/initialData.json

**Comment by kamaldua65** [comment]
Thank you for quick response.  Yes I can login after adding file name to path.
