### ISSUE TITLE
Bug - Change username in a room is not updated in assistants.

### ISSUE THREAD

**Issue by cruizba** [codeurjc-students/2019-OpenViduTeaching#9]
## Deployment info
**OpenVidu Teaching version**: master - https://github.com/codeurjc-students/2019-OpenViduTeaching/commit/11459a631daea8df145a99282401b1450d9f1bec
**Docker Image**: `openvidu/openviduteaching:1.3.0-beta1` 
We've built or own docker image by executing `./create_image.sh` in `https://github.com/codeurjc-students/2019-OpenViduTeaching/tree/master/docker` in order to update OpenVidu Client version to 2.15.0.
## Issue description:
If you update the username while being in a room, the name is updated in the video element, but not the assistants name.
![imagen](https://user-images.githubusercontent.com/7049047/87572695-39964980-c6cc-11ea-870b-45383443260c.png)

**Comment by DiegoMzmn** [comment]
There is a difference beetween the user's *name* and their *nickname*. The name is the one they use for their account, and cannot be changed. Their nickname is the one they have in a room when a session is taking place and can be changed before entering or inside the room. The nickname defaults to the name.
The assistants component displays the names of the users. It's a bit counterintuitive but it's done this way so that even if the nickname is changed everyone (specially moderators) can recognise who really is connected at any moment.
